### PR TITLE
Fix pretest error on windows

### PR DESCRIPTION
**Pull request by p-v-d-Veeken**
Okay, so the entire scripts section of package.json is just one big clusterf--- on Windows. 

First the test script failed because Windows can't into embedded quotes, I fixed it by creating a separate script which gets called from the pretest command. Then, the test script failed, because dark powers are forming and we are powerless to stop Them, I fixed that error by just typing into the terminal and seeing what stuck. Then the prepublish script failed and I decided I had enough for today. 

So yeah, this PR will get you halfway through the scripts section of package.json on Windows. I will see what I can do with the prepublish script, but once again, no promises.

### CODE REVIEW

**Comment by svanschooten** [comment]
Please incorporate this in your next versions. Tests can not bet run on windows. :+1:

**Comment by mbostock** [comment]
Some problems with this PR:

* Removing the `-p` breaks the mkdir command on OS X and Linux.
* Unintended removal of the eslint command.
* Unnecessary change to .gitignore.

I’ll submit a separate fix shortly.

**Comment by mbostock** [comment]
This change needs to be propagated to ~30 other [D3 modules](https://github.com/d3). Please let me know if it works, and then I’ll go ahead and re-apply this commit to the other modules. Thanks.

**Comment by p-v-d-Veeken** [comment]
@mbostock It doesn't work properly yet, see: https://github.com/d3/d3-random/issues/15

**Comment by mbostock** [comment]
Yep, I’m on it.

**Pull request closed without merging**
