### PR TITLE
Poisson process

### PR DESCRIPTION
**Pull request by veltman**
Not sure if this is addition is desired but I figured I'd offer just in case, I end up using a Poisson process to time things like random particles in animations.

### CODE REVIEW

**Comment by mbostock** [comment]
Can you help me understand your choice of implementation? I’m looking at Wikipedia on [generating Poisson-distributed random variables](https://en.wikipedia.org/wiki/Poisson_distribution#Generating_Poisson-distributed_random_variables) and it looks like they’re all iterative solutions.

**Comment by mbostock** [comment]
I think the difference here is terminology. Most other “Poisson random” generators returns a random number from a Poisson distribution, whose value *k* is the number of events occurring within the rate λ.
 (See MathWork’s [poissrnd](https://www.mathworks.com/help/stats/poissrnd.html) and NumPy’s [random.poisson](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.poisson.html).)

But in this case, you’re returning a random time between events in a Poisson process. So it’s useful for simulating a Poisson process, but different than the standard definition.

**Comment by mbostock** [comment]
This should probably be called [expovariate](https://docs.python.org/3/library/random.html#random.expovariate)… or maybe exponential?

**Comment by veltman** [comment]
I think it's just different framings, a distribution of events-per-interval vs. a process generating individual times (e.g. a distribution of hours by number of pedestrians in the hour vs. just generating how many hours until the next pedestrian passes).

This implementation selects a time by selecting a random probability f(x) on the cumulative distribution function and then working backwards to solve for the time, as described here:

http://preshing.com/20111007/how-to-generate-random-timings-for-a-poisson-process/
http://www.fpga-dev.com/properly-time-distributed-stimuli-part-ii/

**Comment by veltman** [comment]
Yes, ^ that. I've never really had a use for generating the distribution in practice, only individual times.  Could certainly rename it to `expovariate`.

**Comment by mbostock** [comment]
I’d prefer the name `exponential`; `expovariate` seems a bit arcane. (And for symmetry, we already use the names `normal` and `logNormal` instead of Python’s `normalvariate` and `lognormvariate`.)

**Comment by veltman** [comment]
Python uses the mean rate as the argument, whereas I currently use the mean interval.

e.g. generating random intervals with a mean of 40 is `random.expovariate(1/40)` and would be `d3.exponential(40)`.

Should I flip it?  The latter seems more intuitive to me but consistency might be best.

**Comment by veltman** [comment]
Switched this to `exponential()` and inverted the argument to be consistent with `expovariate`, let me know what you think.

**Comment by mbostock** [comment]
Almost there. Given that Math.random returns a uniform random variable in [0,1), these two should be equivalent:

```js
-Math.log(1 - Math.random()) / lambda
-Math.log(Math.random()) / lambda
```

And the second is slightly faster and shorter, so we should do that. (See [Generating exponential variates](https://en.wikipedia.org/wiki/Exponential_distribution#Generating_exponential_variates).)

**Comment by mbostock** [comment]
Well, I guess it’s *slightly* different because it’s [0,1) not [0,1]: the first form can return -0 (with a positive lambda, or 0 with a negative lambda), while the second form can return Infinity.

**Comment by veltman** [comment]
I had inverted it so that the resulting random number would be in (0,1] instead, because `Math.log(0)` is `-Infinity`.

**Comment by mbostock** [comment]
I suppose we could do something elaborate like:

```js
var x;
while (!(x = Math.random()));
return -Math.log(x) / lambda;
```

But your solution is simpler and likely sufficient.

LGTM.

**Comment by mbostock** [comment]
Merged and released as 0.1.0. Thank you.

**Pull request merged**
